name: Release

on:
  push:
    tags:
      - 'v*'  # triggers on tags like v1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/unica_sport_bot
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
